#specification of http server request and positive response
config:
    name: cs-bham-forward
    remote: www.cs.bham.ac.uk
    remote-port: 80
    local-port: 80
    test-request: |+
        GET / HTTP/1.1
        Host: www.cs.bham.ac.uk
        User-Agent: Pikachu


    test-response: HTTP/1.1 2\d\d.*
    test-response-length: 16
    #test-response-length is the number of characters to receive and check against the regex
    proxy-mutator-location: mutators/forward.py
    #location of python program for mutator
    proxy-mutate-receive: client_receive
    #this is the name of the function that takes two sockets for the receive journey:
        #receive(a,b)
        # a is the recieving socket from the remote server, and b is the sending socket back to the client
    proxy-mutate-send: client_send 
    #this is similar to the 'proxy-mutate-receive' except for data travelling in the other direction.


