#specification of http server request and positive response
config:
    name: forward 
    remote: localhost 
    remote-port: 2000 
    local-port: 2001 
    test-request: 
    test-response: .* 
    test-response-length: 0
    #test-response-length is the number of characters to receive and check against the regex
    proxy-mutator-location: mutators/forward.py
    #location of python program for mutator
    proxy-mutate-receive: client_receive
    #this is the name of the function that takes two sockets for the receive journey, and a pointer to a function that is used for getting session data:
        #receive(a,b,c)
        # a is the recieving socket from the remote server, and b is the sending socket back to the client
        # c is the function pointer that takes an identifier returns a dictionary of session data - and is thread safe it is up for the mutator to compute the identifier
    proxy-mutate-send: client_send
    #this is similar to the 'proxy-mutate-receive' except for data travelling in the other direction.


