#specification of http server request and positive response
config:
    name: forward 
    remote: localhost 
    remote-port: 2000 
    local-port: 2001 
    test-request: 
    test-response: .* 
    test-response-length: 0
    #test-response-length is the number of characters to receive and check against the regex
    proxy-mutator-location: mutators/mitm.py
    #location of python program for mutator
    proxy-mutate-receive: receive
    #this is the name of the function that takes two sockets for the receive journey:
        #receive(a,b)
        # a is the recieving socket from the remote server, and b is the sending socket back to the client
    proxy-mutate-send: send
    #this is similar to the 'proxy-mutate-receive' except for data travelling in the other direction.


