#specification of http server request and positive response
config:
    name: bbc-weather-http
    page: http
    remote: www.bbc.co.uk
    remote-port: 80
    local-port: 80
    test-request: |+
        GET /weather/ HTTP/1.1
        Host: www.bbc.co.uk
        User-Agent: Pikachu


    test-response: HTTP/1.1 2\d\d.*
    test-response-length: 16
    #test-response-length is the number of characters to recieve and check against the regex



